name: Deploy Application

on: 
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup React Application
        uses: actions/setup-node@v4
        with: 
          node-version: 'latest'

      - name: Install Dependencies
        run: cd my-app && npm ci

      - name: React Build Project
        run: cd my-app && npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t victorrippi/ghactions .

      - name: Push Docker Image
        run: docker push victorrippi/ghactions

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove Old Docker 
        run: docker rm -f deploy_ghactions

      - name: Remove All Not Used Images
        run: docker system prune -a -f 

      - name: Pull Image From DockerHub to EC2 Instance
        run: docker pull victorrippi/ghactions 

      - name: Run Docker Container
        run: docker run -d -p 5173:5173 --name deploy_ghactions victorrippi/ghactions
