name: Deploy Application

on: 
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup React Application
        uses: actions/setup-node@v4
        with: 
          node-version: 'latest'

      - name: Install Dependencies
        run: cd my-app && npm ci

      - name: React Build Project
        run: cd my-app && npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: cd my-app && docker build -t victorrippi/ghactions .

      - name: Push Docker Image
        run: cd my-app && docker push victorrippi/ghactions

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy docker-compose file to EC2
        run: scp -i ${{ secrets.EC2_SSH_KEY }} docker-compose.yml ubuntu@${{ secrets.EC2_INSTANCE }}:/home/ubuntu/docker-compose.yml

      - name: SSH into EC2 and Deploy
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_INSTANCE }} << 'EOF'
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
          EOF
