name: Deploy React Application

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: cd my-app && npm ci

      - name: Build React Application
        run: cd my-app && npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: cd my-app && docker build -t victorrippi/ghactions .

      - name: Push Docker Image
        run: docker push victorrippi/ghactions

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy and Run Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_INSTANCE }} << 'EOF'
          docker pull victorrippi/ghactions
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 3000:3000 --name myapp victorrippi/ghactions
          EOF

      - name: Cleaning Old System 
        run: docker system prune -a -f
